"""ML Training Data Collector — Harvests feature vectors and quality labels
from each RAG Multi-Agent pipeline run.

After every blog generation cycle, this module extracts a structured feature
vector from the GraphState and persists it (with quality labels) into a JSONL
file that can later be consumed by the ML Trainer (ml_trainer.py).

Features are computed entirely from data already available in the pipeline
(zero additional API calls).  Labels are initially generated by an
LLM-as-a-judge approach; once enough data is collected the trained ML model
replaces the LLM judge.
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Default storage path for training data
DEFAULT_TRAINING_DATA_PATH = "data/ml/training_data.jsonl"


# ---------------------------------------------------------------------------
# Feature Extraction
# ---------------------------------------------------------------------------

def _count_headings(draft: str) -> int:
    """Count markdown H2 headings in a draft."""
    return len(re.findall(r"^## ", draft, re.MULTILINE))


def _keyword_density(draft: str, topic: str) -> float:
    """Compute topic keyword density (0.0 – 1.0 scale)."""
    if not draft or not topic:
        return 0.0
    topic_words = set(re.findall(r"\w+", topic.lower()))
    draft_words = re.findall(r"\w+", draft.lower())
    if not draft_words or not topic_words:
        return 0.0
    mentions = sum(1 for w in draft_words if w in topic_words)
    return round(mentions / len(draft_words), 4)


def _flesch_kincaid_grade(text: str) -> float:
    """Approximate Flesch-Kincaid Grade Level (code-only, 0 API tokens)."""
    sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
    if not sentences:
        return 0.0
    words = re.findall(r"[a-zA-Z]+", text)
    if not words:
        return 0.0

    def _syllables(w: str) -> int:
        w = w.lower().strip()
        if len(w) <= 3:
            return 1
        if w.endswith("e"):
            w = w[:-1]
        return max(1, len(re.findall(r"[aeiouy]+", w)))

    total_syllables = sum(_syllables(w) for w in words)
    asl = len(words) / len(sentences)
    asw = total_syllables / len(words)
    return round(max(0.0, 0.39 * asl + 11.8 * asw - 15.59), 2)


def _reading_ease(text: str) -> float:
    """Approximate Flesch Reading Ease score."""
    sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
    if not sentences:
        return 0.0
    words = re.findall(r"[a-zA-Z]+", text)
    if not words:
        return 0.0

    def _syllables(w: str) -> int:
        w = w.lower().strip()
        if len(w) <= 3:
            return 1
        if w.endswith("e"):
            w = w[:-1]
        return max(1, len(re.findall(r"[aeiouy]+", w)))

    total_syllables = sum(_syllables(w) for w in words)
    asl = len(words) / len(sentences)
    asw = total_syllables / len(words)
    return round(max(0.0, min(100.0, 206.835 - 1.015 * asl - 84.6 * asw)), 2)


def _semantic_coherence(draft: str) -> float:
    """Compute semantic coherence between consecutive paragraphs using local embeddings.
    
    Returns average pairwise cosine similarity between adjacent paragraphs.
    Higher = more coherent flow.
    """
    try:
        from app.local_semantics import get_embeddings, cosine_similarity
        paragraphs = [p.strip() for p in draft.split("\n\n") if p.strip() and not p.strip().startswith("#")]
        if len(paragraphs) < 2:
            return 1.0  # Single paragraph = fully coherent
        # Take first 300 chars of each paragraph
        texts = [p[:300] for p in paragraphs[:8]]
        embeddings = get_embeddings(texts)
        similarities = []
        for i in range(len(embeddings) - 1):
            sim = cosine_similarity(embeddings[i], embeddings[i + 1])
            similarities.append(float(sim))
        return round(sum(similarities) / len(similarities), 4) if similarities else 0.5
    except Exception as exc:
        logger.debug("Semantic coherence computation failed: %s", exc)
        return 0.5


def _count_nli_contradictions(draft: str, context: str) -> int:
    """Count sentences in the draft that contradict the retrieved context.

    Uses the Local NLI CrossEncoder (DeBERTa-v3-small) to detect hallucinations.
    Returns the number of sentences flagged as contradictions (0 API tokens).
    """
    if not draft or not context:
        return 0
    try:
        from app.local_nli import get_nli_model
        import numpy as np

        model = get_nli_model()
        sentences = re.split(r'(?<=[.!?])\s+', draft[:3000])
        sentences = [s.strip() for s in sentences if len(s.split()) >= 5]
        if not sentences:
            return 0

        contradictions = 0
        context_truncated = context[:4000]
        for sentence in sentences[:20]:  # Cap at 20 sentences for latency
            try:
                scores = model.predict([context_truncated, sentence])
                probs = np.exp(scores) / np.sum(np.exp(scores), axis=-1, keepdims=True)
                prob_contradiction = float(probs[0])
                prob_entailment = float(probs[1])
                if prob_contradiction > 0.60 and prob_entailment < 0.20:
                    contradictions += 1
            except Exception:
                continue
        return contradictions
    except Exception as exc:
        logger.debug("NLI contradiction counting failed: %s", exc)
        return 0


def extract_features(state: dict[str, Any]) -> dict[str, Any]:
    """Extract the ML feature vector from a completed GraphState.

    Parameters
    ----------
    state : dict
        The final GraphState after a complete RAG pipeline run.

    Returns
    -------
    dict
        A flat dictionary of numeric features suitable for ML training.
    """
    draft = state.get("draft", "")
    parsed = state.get("parsed", {})
    retrieved_docs = state.get("retrieved_docs", [])
    retrieval_meta = state.get("retrieval_meta", {})
    topic = parsed.get("topic", "")

    # -- Retrieval features --
    doc_scores = [float(d.get("score", 0)) for d in retrieved_docs]
    semantic_scores = []
    authority_scores = []
    for d in retrieved_docs:
        if "semantic_score" in d:
            semantic_scores.append(float(d["semantic_score"]))
        # Authority score may be in metadata
        auth = d.get("authority_score", d.get("metadata", {}).get("authority_score", 0.5))
        authority_scores.append(float(auth))

    retrieval_score_mean = round(sum(doc_scores) / len(doc_scores), 4) if doc_scores else 0.0
    retrieval_score_max = round(max(doc_scores), 4) if doc_scores else 0.0
    semantic_score_mean = round(sum(semantic_scores) / len(semantic_scores), 4) if semantic_scores else 0.0
    source_authority_mean = round(sum(authority_scores) / len(authority_scores), 4) if authority_scores else 0.0

    # RAG Evaluator dimensions (if available in retrieval_meta)
    rag_eval = retrieval_meta if isinstance(retrieval_meta, dict) else {}

    # -- Draft / Content features --
    word_count = len(draft.split()) if draft else 0
    heading_count = _count_headings(draft)
    fk_grade = _flesch_kincaid_grade(draft) if draft else 0.0
    read_ease = _reading_ease(draft) if draft else 0.0
    kw_density = _keyword_density(draft, topic)

    # -- Pipeline metadata --
    complexity_score_raw = state.get("supervisor_notes", "")
    complexity_match = re.search(r"score=(\d+)", complexity_score_raw)
    complexity_score = int(complexity_match.group(1)) if complexity_match else 0

    # -- Semantic coherence (local embeddings, 0 API tokens) --
    coherence = _semantic_coherence(draft) if draft and word_count > 50 else 0.5

    # -- NLI Contradiction count (local CrossEncoder, 0 API tokens) --
    context_for_nli = "\n".join(d.get("content", "")[:500] for d in retrieved_docs[:5])
    nli_contradictions = _count_nli_contradictions(draft, context_for_nli) if draft and context_for_nli else 0

    features = {
        # Retrieval features
        "retrieval_doc_count": len(retrieved_docs),
        "retrieval_score_mean": retrieval_score_mean,
        "retrieval_score_max": retrieval_score_max,
        "retrieval_semantic_mean": semantic_score_mean,
        "retrieval_relevance": float(rag_eval.get("relevance", 0.0)),
        "retrieval_coverage": float(rag_eval.get("coverage", 0.0)),
        "retrieval_diversity": float(rag_eval.get("diversity", 0.0)),
        "retrieval_freshness": float(rag_eval.get("freshness", 0.0)),
        "source_authority_mean": source_authority_mean,
        # Draft features
        "draft_word_count": word_count,
        "draft_heading_count": heading_count,
        "draft_fk_grade": fk_grade,
        "draft_reading_ease": read_ease,
        "draft_keyword_density": kw_density,
        "semantic_coherence": coherence,
        "nli_contradictions": nli_contradictions,
        # Pipeline features
        "topic_complexity_score": complexity_score,
        "revision_count": int(state.get("revision_count", 0)),
        "retrieval_attempts": int(state.get("retrieval_attempts", 0)),
    }
    return features


# ---------------------------------------------------------------------------
# Label Generation (LLM-as-a-judge bootstrap)
# ---------------------------------------------------------------------------

def generate_labels_heuristic(state: dict[str, Any], features: dict[str, Any]) -> dict[str, Any]:
    """Generate quality labels using heuristic rules (zero LLM tokens).

    This is the fallback labeling strategy when no LLM judge is available
    or when we want to label data without API cost.

    Parameters
    ----------
    state : dict
        The final GraphState.
    features : dict
        The extracted feature vector.

    Returns
    -------
    dict
        Label dictionary with faithfulness_score, relevance_score, quality_class.
    """
    draft = state.get("draft", "")

    # Heuristic faithfulness: check if draft mentions "Internal data does not"
    from app.langchain_pipeline import MISSING_INTERNAL_DATA_TEXT
    if MISSING_INTERNAL_DATA_TEXT in draft:
        faithfulness = 1.0  # Perfect refusal
    elif features["retrieval_doc_count"] == 0:
        faithfulness = 0.2  # No docs → likely hallucination
    elif features["retrieval_score_mean"] >= 3.0 and features["retrieval_semantic_mean"] >= 0.3:
        faithfulness = 0.85
    elif features["retrieval_score_mean"] >= 2.0:
        faithfulness = 0.65
    else:
        faithfulness = 0.4

    # Heuristic relevance: based on keyword density + heading structure
    if features["draft_keyword_density"] >= 0.01 and features["draft_heading_count"] >= 2:
        relevance = 0.9
    elif features["draft_keyword_density"] >= 0.005:
        relevance = 0.7
    else:
        relevance = 0.4

    # Quality class derived from combined score
    combined = 0.6 * faithfulness + 0.4 * relevance
    if combined >= 0.75:
        quality_class = "high"
    elif combined >= 0.45:
        quality_class = "medium"
    else:
        quality_class = "low"

    return {
        "faithfulness_score": round(faithfulness, 3),
        "relevance_score": round(relevance, 3),
        "quality_class": quality_class,
        "label_source": "heuristic",
    }


def generate_labels_llm_judge(state: dict[str, Any]) -> dict[str, Any] | None:
    """Generate quality labels using LLM-as-a-judge (costs API tokens).

    Returns None if the LLM is unavailable or fails.
    """
    try:
        from app.langchain_pipeline import pipeline
        from langchain_core.messages import SystemMessage, HumanMessage

        llm = getattr(pipeline, "_editor_llm", None) or pipeline._llm
        if llm is None:
            return None

        draft = state.get("draft", "")
        retrieved_docs = state.get("retrieved_docs", [])
        context = "\n\n".join(d.get("content", "")[:500] for d in retrieved_docs[:5])

        system_prompt = (
            "You are a strict RAG quality evaluator. Score the following blog draft.\n"
            "Return ONLY a valid JSON object with exactly these keys:\n"
            '{"faithfulness": <float 0.0-1.0>, "relevance": <float 0.0-1.0>}\n'
            "faithfulness = how well the draft is grounded in the retrieved context.\n"
            "relevance = how well the draft addresses the user's original topic.\n"
            "Do NOT include newlines or special characters inside field values."
        )
        user_prompt = (
            f"### Retrieved Context:\n{context[:3000]}\n\n"
            f"### Generated Draft:\n{draft[:2000]}"
        )

        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt),
        ])
        raw = getattr(response, "content", str(response)).strip()

        # Clean markdown fences
        clean = raw.strip()
        if clean.startswith("```"):
            clean = re.sub(r"^```(?:json)?\n?", "", clean)
            clean = re.sub(r"\n?```$", "", clean)
            clean = clean.strip()

        parsed = json.loads(clean)
        faithfulness = min(1.0, max(0.0, float(parsed.get("faithfulness", 0.5))))
        relevance = min(1.0, max(0.0, float(parsed.get("relevance", 0.5))))

        combined = 0.6 * faithfulness + 0.4 * relevance
        if combined >= 0.75:
            quality_class = "high"
        elif combined >= 0.45:
            quality_class = "medium"
        else:
            quality_class = "low"

        return {
            "faithfulness_score": round(faithfulness, 3),
            "relevance_score": round(relevance, 3),
            "quality_class": quality_class,
            "label_source": "llm_judge",
        }
    except Exception as exc:
        logger.warning("LLM-as-judge labeling failed: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def save_training_record(
    features: dict[str, Any],
    labels: dict[str, Any],
    metadata: dict[str, Any] | None = None,
    output_path: str = DEFAULT_TRAINING_DATA_PATH,
) -> None:
    """Append a single training record (features + labels) to the JSONL file.

    Parameters
    ----------
    features : dict
        The extracted feature vector.
    labels : dict
        The quality labels (faithfulness, relevance, quality_class).
    metadata : dict, optional
        Additional metadata (topic, timestamp, etc.).
    output_path : str
        Path to the JSONL file.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    record = {
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "features": features,
        "labels": labels,
        "metadata": metadata or {},
    }

    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

    logger.info(
        "ML Data Collector: saved training record (quality=%s, source=%s) → %s",
        labels.get("quality_class", "?"),
        labels.get("label_source", "?"),
        output_path,
    )


def collect_from_state(
    state: dict[str, Any],
    use_llm_judge: bool = False,
    output_path: str = DEFAULT_TRAINING_DATA_PATH,
) -> dict[str, Any]:
    """Full collection pipeline: extract features → generate labels → save.

    Parameters
    ----------
    state : dict
        The final GraphState after a complete RAG pipeline run.
    use_llm_judge : bool
        If True, attempt LLM-as-judge labeling first (costs API tokens).
        Falls back to heuristic labels on failure.
    output_path : str
        Path to persist the training record.

    Returns
    -------
    dict
        The extracted features (also stored in state as ml_features).
    """
    features = extract_features(state)

    # Generate labels
    labels = None
    if use_llm_judge:
        labels = generate_labels_llm_judge(state)

    if labels is None:
        labels = generate_labels_heuristic(state, features)

    # Metadata for traceability
    parsed = state.get("parsed", {})
    metadata = {
        "topic": parsed.get("topic", ""),
        "intent": parsed.get("intent", ""),
        "complexity_level": state.get("complexity_level", "simple"),
        "request_id": state.get("request_id", ""),
    }

    save_training_record(features, labels, metadata, output_path)

    return {
        "ml_features": features,
        "ml_labels": labels,
    }


def count_training_records(path: str = DEFAULT_TRAINING_DATA_PATH) -> int:
    """Count the number of training records in the JSONL file."""
    p = Path(path)
    if not p.exists():
        return 0
    count = 0
    for line in p.read_text(encoding="utf-8").splitlines():
        if line.strip():
            count += 1
    return count


# ---------------------------------------------------------------------------
# Failure Diagnosis (for Dual-Scope Routing)
# ---------------------------------------------------------------------------

def diagnose_failure_source(features: dict[str, Any]) -> str:
    """Analyze features to determine if quality failure is due to
    retrieval issues or generation issues.

    Returns
    -------
    str
        'retrieval' — low retrieval quality → route back to Researcher
        'generation' — low draft quality → route back to Writer
        'both' — both retrieval and generation are weak
        'none' — no clear failure detected
    """
    # Retrieval quality indicators
    retrieval_weak = (
        features.get("retrieval_relevance", 0) < 0.4
        or features.get("retrieval_coverage", 0) < 0.4
        or features.get("retrieval_doc_count", 0) < 2
    )

    # Generation quality indicators
    generation_weak = (
        features.get("nli_contradictions", 0) >= 2
        or features.get("draft_fk_grade", 0) > 14
        or features.get("draft_reading_ease", 100) < 30
        or features.get("semantic_coherence", 1) < 0.3
    )

    if retrieval_weak and generation_weak:
        return "both"
    elif retrieval_weak:
        return "retrieval"
    elif generation_weak:
        return "generation"
    return "none"
